# Generated by Django 2.2.1 on 2019-10-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isPatient',
            field=models.BooleanField(default=True),
        ),
    ]
