# Generated by Django 2.2.1 on 2019-10-31 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('Register', '0002_user_ispatient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
