# Generated by Django 2.2.1 on 2019-11-01 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0004_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
