# Generated by Django 2.2.1 on 2019-11-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0007_auto_20191109_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
