# Generated by Django 2.2.1 on 2019-11-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0008_patient_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='', max_length=23),
        ),
        migrations.AddField(
            model_name='patient',
            name='previous_symptoms',
            field=models.CharField(default='', max_length=112),
        ),
    ]
